### ISSUE TITLE
修理中イベントのバグ

### ISSUE THREAD

**Issue by Maple-32768** [MarshmallowJava/KillerEscape#2]
修理中イベント **#killerescape:on_repairing** は修理中ではない状態で呼び出されることがあります。現在のところ判明しているのは以下の場合です。

1. 修理キットを持って右クリックした時

このイベントは生存者が発電機を修理した時にのみ呼び出されることが期待されます。

**Comment by MarshmallowJava** [comment]
実際に修理された通信機が存在している場合のみ作動するよう修正しました。
